# Generated by Django 5.0.6 on 2024-06-24 12:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("map", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Randonnee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("difficulte", models.CharField(max_length=1)),
                ("distance_parcourue", models.FloatField()),
                ("duree_minutes_total", models.IntegerField()),
                ("altitude_min", models.IntegerField()),
                ("altitude_max", models.IntegerField()),
                ("location_lon", models.FloatField(blank=True, null=True)),
                ("location_lat", models.FloatField(blank=True, null=True)),
                ("is_ouvert", models.CharField(max_length=3)),
                ("zone_translations_item_nom", models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name="PointOfInterest",
        ),
    ]
