# Generated by Django 5.0.6 on 2024-07-03 12:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("map", "0004_commune"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commune",
            name="insee_arr",
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name="commune",
            name="insee_can",
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name="commune",
            name="insee_com",
            field=models.IntegerField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name="commune",
            name="insee_dep",
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name="commune",
            name="insee_epci",
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name="commune",
            name="insee_reg",
            field=models.IntegerField(max_length=10),
        ),
    ]
