# Generated by Django 5.0.6 on 2024-07-03 12:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("map", "0005_alter_commune_insee_arr_alter_commune_insee_can_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commune",
            name="insee_arr",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="commune",
            name="insee_can",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="commune",
            name="insee_com",
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name="commune",
            name="insee_dep",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="commune",
            name="insee_epci",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="commune",
            name="insee_reg",
            field=models.IntegerField(),
        ),
    ]
